// These are callbacks (delegates) that can be used by the messengers defined
// in EventHandler.cs.

public delegate void Callback(System.Object arg);

#region Event Types enum
public enum EEventID
{
    EVENT_LOAD_LEVEL,

    EVENT_TOUCH_TAP,
    EVENT_TOUCH_SWIPE,
    EVENT_TOUCH_PINCH,
    EVENT_TOUCH_DRAG,
    EVENT_TOUCH_DOUBLE_TAP,
    EVENT_TOUCH_START,
    EVENT_TOUCH_TWO_FINGER_START,
    EVENT_TOUCH_TWO_FINGER_MOVING,
    EVENT_TOUCH_MOVING,
    EVENT_TOUCH_STATIONARY,
    EVENT_TOUCH_END,
    EVENT_POINTER_DRAG,
    EVENT_TOUCH_COUNT_CHANGE,

    EVENT_TOUCH_IMMEDIATE,
    
    EVENT_HOLD_LEFT,
    EVENT_HOLD_RIGHT,
    EVENT_LEAVE_LEFT,
    EVENT_LEAVE_RIGHT,
    EVENT_JUMP,

    EVENT_KEY_A,
    EVENT_KEY_D,
    EVENT_KEY_SPACE,
    EVENT_KEY_END,
    EVENT_KEY_START,
    EVENT_KEY_LSHIFT,
    //EVENT_POINTER_DRAG,
    EVENT_MOUSE_START,
    EVENT_MOUSE_END,
    EVENT_KEY_ESCAPE,

    EVENT_GESTURE_TRIANGLE,
    EVENT_GESTURE_SQUARE,
    EVENT_GESTURE_CIRCLE,
    EVENT_PLAYER_VELOCITY,
    EVENT_TOGGLE_DRAW_TRAIL,
    EVENT_GESTURE_OBJET_DESTROY,
    EVENT_GESTURE_OBJECT_CREATE,

    EVENT_COLLISION_ENTER,
    EVENT_COLLISION_STAY,
    EVENT_COLLISION_EXIT,

    EVENT_MOVE_CAMERA,
    EVENT_CHILD_COLLISION,
    EVENT_CHILD_TRIGGER,

    EVENT_TRIGGER_TUTORIAL,
    EVENT_PLAYER_STATE_CHANGE,
    EVENT_PLAYER_STATE_UPDATE,
    EVENT_UPDATE_SAVE_POSITION,
    EVENT_SHOW_PROMPT_MSG,
    EVENT_UPDATE_GESTURE_UI,
    EVENT_GESTURE_WORLD_POINT,
    EVENT_SET_GESTURE_PREFAB,
    EVENT_ENABLE_GESTURE_DETECTION,

    EVENT_DESTROY_ENEMY,
	//------------------------------//
	EVENT_COUNT,//PLEASE NOTE:Please keep this as last vlaue in ENUM, Count of enum
}
#endregion
